import streamlit as st
import random

st.set_page_config(page_title="FunFetch 🐶", page_icon="🐶")

st.title("🐶 Welcome to FunFetch!")
st.write("Your smart doggo is here to fetch you fun facts one bark at a time! 🧠🐾")

if "facts_seen" not in st.session_state:
    st.session_state.facts_seen = 0

facts = [
    "A shrimp’s heart is in its head! 🦐",
    "Bananas are berries, but strawberries aren’t! 🍌",
    "Octopuses have three hearts! ❤️❤️❤️",
    "Honey never spoils — it lasts forever! 🍯",
    "Sloths can hold their breath longer than dolphins! 😮",
    "Wombat poop is cube-shaped! 🟫",
    "Sharks existed before trees did! 🌳🦈",
    "Cows have best friends and get sad when they're apart. 🐄",
    "There are more stars in space than grains of sand on Earth. ✨",
    "Some turtles can breathe through their butts. 🐢💨",
    "You can hear a blue whale’s heartbeat from 2 miles away. 🐋",
    "A day on Venus is longer than a year on Venus. 🪐",
    "Elephants can’t jump. 🐘",
    "The Eiffel Tower can grow 6 inches in summer from heat. 🌡️",
    "Some frogs can freeze solid and come back to life! 🐸❄️",
    "Butterflies can taste with their feet. 🦋",
    "There’s a basketball court on top of the U.S. Supreme Court. 🏀",
    "Rabbits can’t vomit. 🐇",
    "Ants don’t sleep. 🐜",
    "Otters hold hands while sleeping so they don’t float away. 🦦",
    "Tigers have striped skin, not just striped fur. 🐅",
    "Apples float because 25% of their volume is air! 🍎",
    "Koalas have fingerprints like humans. 🐨",
    "A group of flamingos is called a 'flamboyance'. 🦩",
    "Snails can sleep for 3 years. 🐌",
    "It rains diamonds on Jupiter and Saturn. 💎",
    "Caterpillars completely liquefy inside their cocoons. 🐛",
    "Peanuts are not nuts — they're legumes. 🥜",
    "A bolt of lightning is five times hotter than the sun. ⚡",
    "Dogs can smell your feelings. 🐶",
    "Octopuses have blue blood. 🐙",
    "Slugs have four noses. 🐌",
    "Most wasabi served in restaurants is actually horseradish. 🌿",
    "The wood frog can hold its pee for up to 8 months! 🐸",
    "The unicorn is the national animal of Scotland. 🦄",
    "A jiffy is an actual unit of time (1/100th of a second). ⏱️",
    "Pigeons can do math. 🐦➕",
    "A baby puffin is called a puffling. 🐣",
    "An eagle can kill a young deer and fly away with it. 🦅",
    "Starfish can regrow arms. ⭐",
    "Kangaroos can't walk backward. 🦘",
    "There are more fake flamingos in the world than real ones. 🦩",
    "A crocodile can’t stick its tongue out. 🐊",
    "The blob of toothpaste on your toothbrush is called a nurdle. 🪥",
    "Mice sing to each other. 🐭🎵",
    "A group of hedgehogs is called a prickle. 🦔",
    "Polar bears have black skin under their white fur. 🐻‍❄️",
    "A cloud can weigh over a million pounds. ☁️",
    "Goats have rectangular pupils. 🐐",
    "Sharks are older than dinosaurs. 🦈",
    "Baby elephants suck their trunks like thumbs. 🐘",
    "Bats always turn left when exiting a cave. 🦇",
    "Giraffes only need 5–30 minutes of sleep per day. 🦒",
    "Water can boil and freeze at the same time. 💧",
    "You can't hum while holding your nose. 🤐",
    "Humans share 60% of their DNA with bananas. 🍌",
    "The longest hiccuping spree lasted 68 years. 😮‍💨",
    "Jellyfish don’t have brains. 🪼",
    "There’s a basketball league for people under 5'4\". 🏀",
    "You can’t tickle yourself. 😄",
    "A day on Mercury is 176 Earth days long. ☀️",
    "Spiders can’t fly — but they can 'balloon' through the air. 🕷️",
    "Cows have almost 360-degree vision. 🐄",
    "Penguins propose with pebbles. 🐧💍",
    "Rats laugh when you tickle them. 🐀😂",
    "A blobfish looks normal underwater — only ugly at the surface. 🐡",
    "Hot water freezes faster than cold water. 🧊",
    "Your nose can remember 50,000 different smells. 👃",
    "The moon has moonquakes. 🌕",
    "A baby octopus is the size of a flea. 🐙",
    "The 'M's in M&M’s stand for Mars & Murrie. 🍬",
    "Humans glow in the dark (just too dim to see). ✨",
    "Turtles can live over 100 years. 🐢",
    "The inventor of the Pringles can is buried in one. 🥔",
    "Jellybeans shine because of shellac — from bug secretions! 🪳",
    "A group of crows is called a murder. 🐦",
    "The Eiffel Tower can shrink by 6 inches in the cold. ❄️",
    "The average person walks the equivalent of 5 times around the world in their lifetime. 🌍",
    "Bees can recognize human faces. 🐝",
    "There's a species of lizard that can squirt blood from its eyes. 🦎😳",
    "Goosebumps are meant to make animals look bigger. 😾",
    "Dolphins give each other names. 🐬",
    "Tomatoes were once thought to be poisonous. 🍅",
    "There's a species of fish that can climb trees. 🐟🌳",
    "Birds don’t urinate. 🐦🚫",
    "The largest snowflake ever recorded was 15 inches wide. ❄️",
    "Blue eyes are more sensitive to light. 👀",
    "Some fungi create zombies — then control their minds. 🍄🧟",
    "Your tongue is made of eight muscles. 👅",
    "Ketchup used to be sold as medicine. 🍅💊",
    "In Japan, letting a sumo wrestler make your baby cry is good luck. 🇯🇵",
    "Cats can't taste sweetness. 🐱🍭❌",
    "You burn more calories sleeping than watching TV. 🛌📺",
    "The dot over the lowercase 'i' is called a 'tittle'. 🔡",
    "There's a town in Norway where the sun doesn’t rise for 6 months. 🌌",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread. ⚡🍞",
    "Bubble wrap was originally invented as wallpaper. 🫧🧱",
    "Pineapples take two years to grow. 🍍",
    "Seahorses mate for life and hold tails when they travel. 🐠❤️",
    "The smell of freshly cut grass is actually a plant distress signal. 🌱😱",
    "The Guinness World Records book is also a record holder — for being stolen most from libraries! 📚🏃"
]

st.subheader(f"🐾 You've discovered {st.session_state.facts_seen} facts with FunFetch!")

if st.button("🐶 Fetch a Fact!"):
    st.session_state.facts_seen += 1
    st.success(random.choice(facts))

st.image("https://cdn-icons-png.flaticon.com/512/616/616408.png", width=120, caption="🐶 FunFetch — Fetching facts since 2024!")
